[package]
name = "maa-callback"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
maa-types.workspace = true
